# Generated by Django 2.1.8 on 2019-05-28 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notepad',
            name='notes',
        ),
        migrations.AlterField(
            model_name='notepad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 10, 35, 34, 578691)),
        ),
        migrations.RemoveField(
            model_name='notepad',
            name='participants',
        ),
        migrations.AddField(
            model_name='notepad',
            name='participants',
            field=models.ManyToManyField(blank=True, to='participant.Participant'),
        ),
    ]
