# Generated by Django 2.1.8 on 2019-05-28 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_auto_20190528_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 11, 30, 22, 485111)),
        ),
    ]
