# Generated by Django 2.1.8 on 2019-05-29 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0005_auto_20190528_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 18, 16, 38, 713135)),
        ),
    ]
