# Generated by Django 2.1.8 on 2019-06-01 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0006_auto_20190529_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 46, 49, 452405)),
        ),
    ]
