# Generated by Django 2.1.8 on 2019-06-03 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0007_auto_20190601_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 7, 31, 12, 236084)),
        ),
    ]
