# Generated by Django 2.1.8 on 2019-05-24 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 5, 24, 19, 32, 8, 563395))),
                ('content', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
