# Generated by Django 2.1.8 on 2019-05-28 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20190528_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 10, 45, 7, 859587)),
        ),
    ]
