# Generated by Django 2.1.8 on 2019-05-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20190528_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
